### PR TITLE
added harmony os code

### PR DESCRIPTION
**Pull request by prasanta352**

### CODE REVIEW

**Review by sharathks84 — COMMENTED** [review]
1. License file is missing and 
2. Fade and FadeScale is not working
3. Tick is getting added continuosly

**Comment by prasanta352** [comment]
> 3\. Tick is getting added continuosly

1. here is the licence https://github.com/prasanta352/StateLayout/tree/hmos-code#license
2. fade and fadeScale is just a switch you have to select a effect(fade/fadeScale) and then click the left options
3. can you give me a video or screenshot for "Tick is getting added continuosly"

**Comment by prasanta352** [comment]
> Tick is getting added continuosly

I have changed the logic for switching between animation type now it should be fixed

**Review by sharathks84 — APPROVED** [review]
OK, Approved

**Review by Gleelakrishna — APPROVED** [review]
ok

**Pull request merged**
